### ISSUE TITLE
Add option to remove long silences from syncmap

### ISSUE THREAD

**Issue by readbeyond** [readbeyond/aeneas#116]
Mainly for CC purposes.

The user must specify the minimum length of the pause to be removed.

Also let the user specify a string (e.g., "[pause]" or "[silence]")? Not sure.

**Comment by jonasoesch** [comment]
I have often seen `<sil>` in other tools. The [IPA proposes](https://en.wikipedia.org/wiki/Extensions_to_the_International_Phonetic_Alphabet#Prosodic_notation) `(...)`

**Comment by pettarin** [comment]
Hi, thank you for the note. Yes, indeed the best option seems to leave the user specify the string she wants, or a placeholder like `REMOVE` if the user prefers the silence to be cut out from the sync map: this is the case of CC (or, at least, of the organization which requested this feature).

**Comment by readbeyond** [comment]
Added in devel. Closing.
