### ISSUE TITLE
aeneas_execute_job with absolute paths

### ISSUE THREAD

**Issue by hobodrifterdavid** [readbeyond/aeneas#176]
I'm using aeneas with aeneas-vagrant. To get aeneas to read input and output to the shared folder (/vagrant on the VM) I use:

aeneas_execute_job /vagrant/frD/fr0.mp3 ...

I get: [ERRO] Directory '../../vagrant/frD/fr0' does not exist
In the VM shell I can see these files fine. I think it's to do with how you are joining the paths. I was taking a little look at the code.

Also tried:

aeneas_execute_job ../../vagrant/frD/fr0.mp3 ...

Doesn't work either though.

Works great otherwise. :-)

**Comment by readbeyond** [comment]
aeneas_execute_job processes an aeneas Job, that is, a compressed (e.g., 
a ZIP file) or uncompressed (i.e., a directory) container of several tasks.

(In fact, the error says "DIRECTORY" '../../vagrant/frD/fr0' does not 
exist...)

I guess you wanted to use aeneas_execute_task (note: _task, not _job).

Please review the docs for the difference:

https://www.readbeyond.it/aeneas/docs/clitutorial.html#processing-tasks

vs

https://www.readbeyond.it/aeneas/docs/clitutorial.html#processing-jobs

HTH,

AP

**Comment by hobodrifterdavid** [comment]
Silly me, I'll try it. Thanks for the response.

**Comment by readbeyond** [comment]
No problem, you are welcome.

This confusion denotes an issue on the design side, and in fact I am not 
fully satisfied by having two separate tools, with confusingly similar 
names.

(I am not really sure if I want to keep the concept of "Job" in aeneas 
v2: if not, I will remove the aeneas_execute_job tool altogether. Maybe 
I will have a single command line tool able to infer whether a Task or a 
Job is being processed. There are PROs and CONs on both ways.)

AP

**Comment by hobodrifterdavid** [comment]
I was lazy to write an XML batch file (I might have done a JSON file though), so I called the command from a python script. It's tricky with the quotes. For reference, this works:
	
parameterString = "'task_language=eng|os_task_file_format=json|is_text_type=plain'"
# Single quotes inside double quotes

command = 'vagrant ssh -c "cd /vagrant; aeneas_execute_task ' + mp3Path + " " + textPath + " " + parameterString + " " + jsonPath + '"'
# That last bit was single/double/single quotes

os.system(command)

Just an idea, maybe not a good one: you could make python 'stubs' for the aeneas commands that live in the aeneas-vagrant folder. All these do if forward the arguments to the real aeneas commands in the VM via ssh -c. I think ssh -c is not set up to print stderr to the terminal from the VM child process, only stdin. Not quite sure though. Like this, it's really almost like having aeneas installed locally.. I had difficulties installed aeneas natively on ubuntu 16.04 (such issues are understandable). Although, it's probably confusing for the user that they can't specify input files outside of the aeneas-vagrant folder. Ah, forget it. If I have a better idea I'll let you know. :-)

**Comment by readbeyond** [comment]
Hi,

I am closing this ticket, as the original issue is resolved.

About quotes: I guess that depends on both the shell convention of the host OS and the bash shell inside the VM. Thank you for noting what actually works for future reference.

About the "stubs": I opened the following issue: https://github.com/readbeyond/aeneas-vagrant/issues/8#issue-228459468 since it concerns aeneas-vagrant rather than aeneas per se. Let's continue the converation there.

Thank you,

AP
