### ISSUE TITLE
Bug, short words be eaten by long words, results in mis-synced text/audio

### ISSUE THREAD

**Issue by jarodtang** [readbeyond/aeneas#193]
Hi, there, i'm trying to use aeneas to sync text audio on a long mp3, meet a issue, could you help  fix this?

for example, put some text as following, I found the sound of 'second_sub' was put into scope of first_sub, and there's no sound or less than enough sound for second_sub.

first_sub - "I just feel like someone reached down my throat, grabbed my small intestine, pulled it out of my mouth and tied it around my neck..." 
second_sub - "Cookie?"

with following codes

`

	config = u"task_language=eng|is_audio_file_head_length=%f|is_audio_file_process_length=%f|mfcc_mask_nonspeech=True|mfcc_mask_extend_speech_after=1|mfcc_window_length=0.100|mfcc_window_shift=0.020"%(heading_time, duration)
	
	task = Task(config_string=config)

	textfile = TextFile()

	for identifier, frag_text in [ (u"f001", [u"%s"%first_sub]), (u"f002", [u"%s"%second_sub]),]:
		textfile.add_fragment(TextFragment(identifier, Language.ENG, frag_text, frag_text))

	task.text_file = textfile
	task.audio_file_path_absolute = u"%s"%mp3Filename

	ExecuteTask(task).execute()
`

Thanks,
Jarod

**Comment by readbeyond** [comment]
Hi,

you might want to read:

https://github.com/readbeyond/aeneas#a-note-on-word-level-alignment

Beyond that, it is hard to tell what's going on without the actual audio 
file. I am a bit puzzled by the fact that you first say that you are 
working on a "long mp3", then you produce an example with a relatively 
short text.

HTH,

AP

**Comment by jarodtang** [comment]
Hi,

the code is here, and tested mp3 file as attachment.

`
def split_dialogue_time_tag(startTime, endTime, first_sub, second_sub, mp3Filename):
	
	duration = string_time_to_float(endTime) - string_time_to_float(startTime)
		
	config = u"task_language=eng|is_audio_file_head_length=%f|is_audio_file_process_length=%f"%(string_time_to_float(startTime), string_time_to_float(endTime) - string_time_to_float(startTime))
	# rc_config = u"mfcc_window_length=0.100|mfcc_window_shift=0.005|mfcc_mask_nonspeech=True"
	# rc = RuntimeConfiguration(config_string=rc_config)

	task = Task(config_string=config) #, rconf=rc)

	textfile = TextFile()

	for identifier, frag_text in [ (u"f001", [u"%s"%first_sub]), (u"f002", [u"%s"%second_sub]),]:
		textfile.add_fragment(TextFragment(identifier, Language.ENG, frag_text, frag_text))

	task.text_file = textfile
	task.audio_file_path_absolute = u"%s"%mp3Filename

	# print task.rconf
	# print task
	ExecuteTask(task).execute()

	return float_to_string_time(task.sync_map_leaves()[1].end)
`

and I tested as following code

`
def print_split_time(start, end, text1, text2):
	split_at = split_dialogue_time_tag(start, end, text1, text2, "101.mp3")
	print start, ' - ', str(split_at), ' - ', end

print_split_time("00:02:30,55", 
				"00:02:39,85", 
				'I just feel like someone reached down my throat, grabbed my small intestine, pulled it out of my mouth and tied it around my neck...', 
				'Cookie?')

print_split_time("00:02:55,07",
				"00:02:59,70", 
				"No, just leave my aura alone, okay?", 
				"Fine!  Be murky!")

print_split_time("00:04:32,77",
				"00:04:36,67", 
				"Can I get you some coffee?", 
				"De-caff.")
`


[101.mp3.zip](https://github.com/readbeyond/aeneas/files/1609369/101.mp3.zip)

**Comment by jarodtang** [comment]
The full test code as following

`

#!/usr/bin/env python
# coding=utf-8

import os
import re
from aeneas.executetask import ExecuteTask
from aeneas.task import Task
from aeneas.textfile import TextFile, TextFragment, TextFileFormat
from aeneas.exacttiming import TimeValue
from aeneas.runtimeconfiguration import RuntimeConfiguration
from aeneas.language import Language
import time
from segtok.tokenizer import word_tokenizer, symbol_tokenizer, space_tokenizer


def split_dialogue_time_tag(startTime, endTime, first_sub, second_sub, mp3Filename):
	
	duration = string_time_to_float(endTime) - string_time_to_float(startTime)
		
	config = u"task_language=eng|is_audio_file_head_length=%f|is_audio_file_process_length=%f"%(string_time_to_float(startTime), string_time_to_float(endTime) - string_time_to_float(startTime))
	# rc_config = u"mfcc_window_length=0.100|mfcc_window_shift=0.005|mfcc_mask_nonspeech=True"
	# rc = RuntimeConfiguration(config_string=rc_config)

	task = Task(config_string=config) #, rconf=rc)

	textfile = TextFile(file_format=TextFileFormat.MPLAIN)

	for identifier, frag_text in [ (u"f001", [u"%s"%first_sub]), (u"f002", [u"%s"%second_sub]),]:
		textfile.add_fragment(TextFragment(identifier, Language.ENG, frag_text, frag_text))

	task.text_file = textfile
	task.audio_file_path_absolute = u"%s"%mp3Filename

	# print task.rconf
	# print task
	ExecuteTask(task).execute()

	return float_to_string_time(task.sync_map_leaves()[1].end)

def string_time_to_float(srtTime) :
	srtTime = re.match( r'^([\d]*):([\d]*):([\d]*),([\d]*)', srtTime.strip(), re.M|re.I)
	return float(srtTime.group(1)) * 3600 + float(srtTime.group(2)) * 60 + float(srtTime.group(3)) + float('0.' + str(srtTime.group(4)))

def float_to_string_time(aeneasTime):
	mill_seconds = str(aeneasTime).split('.')

	m, s = divmod(int(aeneasTime), 60)
	h, m = divmod(m, 60)
	
	return  "%02d:%02d:%02d,%02d"% (h, m, s, int(mill_seconds[1]))



def print_split_time(start, end, text1, text2):
	split_at = split_dialogue_time_tag(start, end, text1, text2, "101.mp3")
	print start, ' - ', str(split_at), ' - ', end

print_split_time("00:02:30,55", 
				"00:02:39,85", 
				'I just feel like someone reached down my throat, grabbed my small intestine, pulled it out of my mouth and tied it around my neck...', 
				'Cookie?')

# print_split_time("00:02:55,07",
# 				"00:02:59,70", 
# 				"No, just leave my aura alone, okay?", 
# 				"Fine!  Be murky!")

# print_split_time("00:04:32,77",
# 				"00:04:36,67", 
# 				"Can I get you some coffee?", 
# 				"De-caff.")
`

**Comment by readbeyond** [comment]
Your code is messed up, and I am not going to try deciphering it from 
the current rendering. If you care, please fix it using the proper 
markdown syntax. (See: 
https://guides.github.com/features/mastering-markdown/ )

However, I downloaded your MP3, and in all three your examples, there is 
laughter in proximity of the "wrong" segmentation you report. I guess 
that that, combined with the fact that you have set a very small MFCC 
shift, gets the aligner confused. Have you tried setting different 
thresholds, e.g. for the VAD parameter, with the goal of having the 
non-speech parts --- i.e., the laughter --- masked out?

AP

**Comment by jarodtang** [comment]
sorry for the messed up, and I attach the test python as  attached zip file.

I agree the laughter confused the algorithm,  i tried to setup the VADs , the result is the same(not changed). 

`	
        rc[RuntimeConfiguration.VAD_MIN_NONSPEECH_LENGTH] = 1.000
`

Jarod

[test_sync.py.zip](https://github.com/readbeyond/aeneas/files/1617060/test_sync.py.zip)

**Comment by readbeyond** [comment]
I might have some time to look at it next Sunday, but I would be not too 
optimistic about a possible solution. The current algorithmic approach 
is probably too rough to distinguish laughter from speech.

AP

**Comment by jarodtang** [comment]
Maybe a asr sync better for this case?

**Comment by readbeyond** [comment]
Sorry, I did not have time to play with the parameters, but I doubt you 
can get both 5ms accuracy and robust dealing of the laughter, with the 
current approach in aeneas.

Perhaps HMMs based aligners can do better, although I would not vouch 
for them on the only basis that their approach is more sophisticated. I 
have seen many YouTube videos whose auto-captions are garbage... You can 
try, e.g. Gentle which has a Web interface that you can try without 
installing anything.

AP

**Comment by jarodtang** [comment]
thanks, I'll try
