### ISSUE TITLE
Installation python 3 error

### ISSUE THREAD

**Issue by benjisympa** [readbeyond/aeneas#195]
Good morning,

Thanks for your work.
I  have install the tool with python 2 but I want to install it with python 3 but I have difficulties.
Have you already got theses errors ?
Thanks.

creating build/temp.macosx-10.7-x86_64-3.6
  creating build/temp.macosx-10.7-x86_64-3.6/aeneas
  creating build/temp.macosx-10.7-x86_64-3.6/aeneas/cdtw
  creating build/temp.macosx-10.7-x86_64-3.6/aeneas/cint
  compile options: '-I/Users/maurice/anaconda3/envs/py3/lib/python3.6/site-packages/numpy/core/include -I['/Users/maurice/anaconda3/envs/py3/lib/python3.6/site-packages/numpy/core/include'] -I/Users/maurice/anaconda3/envs/py3/include/python3.6m -c'
  gcc: aeneas/cdtw/cdtw_py.c
  zsh:1: no matches found: -I[/Users/maurice/anaconda3/envs/py3/lib/python3.6/site-packages/numpy/core/include]
  zsh:1: no matches found: -I[/Users/maurice/anaconda3/envs/py3/lib/python3.6/site-packages/numpy/core/include]
  error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/maurice/anaconda3/envs/py3/include -arch x86_64 -I/Users/maurice/anaconda3/envs/py3/include -arch x86_64 -I/Users/maurice/anaconda3/envs/py3/lib/python3.6/site-packages/numpy/core/include -I['/Users/maurice/anaconda3/envs/py3/lib/python3.6/site-packages/numpy/core/include'] -I/Users/maurice/anaconda3/envs/py3/include/python3.6m -c aeneas/cdtw/cdtw_py.c -o build/temp.macosx-10.7-x86_64-3.6/aeneas/cdtw/cdtw_py.o" failed with exit status 1

  ----------------------------------------
  Failed building wheel for aeneas
  Running setup.py clean for aeneas
Failed to build aeneas

**Comment by readbeyond** [comment]
Maybe this is related to https://github.com/readbeyond/aeneas/pull/191 , but I cannot really tell, as I do not use (ana)conda. What was the exact command that produced the log you provided above? Are you working inside a (ana)conda virtual env, I guess, right?

**Comment by benjisympa** [comment]
Thank you for your answer. Sry for my delay. I just write pip install aeneas in a virtual env (source activate). I think it's the same but than #191. Do you find a solution for this ? Thanks

**Comment by boltomli** [comment]
#191 resolved this

**Comment by pettarin** [comment]
OK, I really need to find time to merge #191 the upcoming weekend.

**Comment by readbeyond** [comment]
Should be solved, closing.
