### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yuxi0321** [readbeyond/aeneas#196]
Thank you so much for your work!

I have tried to install aeneas with both Python2 and Python3 but all failed in the end. The following is the details of the error. Could you please me check what is the reason for the failure?

Failed building wheel for aeneas
  Running setup.py clean for aeneas
Failed to build aeneas
Installing collected packages: aeneas
  Running setup.py install for aeneas ... error
    Complete output from command /usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/xb/g15nz0cs7454zz7hcj8lp2v80000gn/T/pip-build-uobew6o9/aeneas/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/xb/g15nz0cs7454zz7hcj8lp2v80000gn/T/pip-42yuuttg-record/install-record.txt --single-version-externally-managed --compile:
    [INFO] *********************************************************************************
    [INFO] Compiling the C extension cew on Mac OS X is experimental.
    [INFO]
    [INFO] Before installing aeneas with cew, you must run:
    [INFO] $ brew update && brew upgrade --cleanup espeak
    [INFO] to run the new brew formula installing libespeak, the library version of espeak.
    [INFO]
    [INFO] If you experience problems, disable cew compilation by specifying
    [INFO] the environment variable AENEAS_WITH_CEW=False .
    [INFO] Please see the aeneas installation documentation for details.
    [INFO] ********************************************************************************
    [INFO]
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.11-x86_64-3.6
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/adjustboundaryalgorithm.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/analyzecontainer.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/audiofile.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/audiofilemfcc.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/cewsubprocess.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/configuration.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/container.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/diagnostics.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/downloader.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/dtw.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/exacttiming.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/executejob.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/executetask.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/ffmpegwrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/ffprobewrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/globalconstants.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/globalfunctions.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/hierarchytype.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/idsortingalgorithm.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/job.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/language.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/logger.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/mfcc.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/plotter.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/runtimeconfiguration.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/sd.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/synthesizer.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/task.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/textfile.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/tree.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/vad.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/validator.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/wavfile.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/cdtw
    copying aeneas/cdtw/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cdtw
    copying aeneas/cdtw/cdtw_setup.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cdtw
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/cew
    copying aeneas/cew/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cew
    copying aeneas/cew/cew_setup.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cew
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/cfw
    copying aeneas/cfw/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cfw
    copying aeneas/cfw/cfw_setup.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cfw
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/cmfcc
    copying aeneas/cmfcc/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cmfcc
    copying aeneas/cmfcc/cmfcc_setup.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cmfcc
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/cwave
    copying aeneas/cwave/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cwave
    copying aeneas/cwave/cwave_setup.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cwave
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/extra
    copying aeneas/extra/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/extra
    copying aeneas/extra/ctw_espeak.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/extra
    copying aeneas/extra/ctw_speect.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/extra
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/format.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/fragment.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/fragmentlist.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/headtailformat.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/missingparametererror.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfaudacity.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfbase.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfcsv.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfeaf.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfgsubtitles.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfgtabular.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfgxml.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfjson.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfrbse.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfsmil.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfsrt.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfssv.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfsub.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smftextgrid.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smftsv.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfttml.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smftxt.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfvtt.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfxml.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    copying aeneas/syncmap/smfxmllegacy.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/syncmap
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/abstract_cli_program.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/convert_syncmap.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/download.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/execute_job.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/execute_task.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/extract_mfcc.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/ffmpeg_wrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/ffprobe_wrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/hydra.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/plot_waveform.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/read_audio.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/read_text.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/run_sd.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/run_vad.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/synthesize_text.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/tools/validate.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/ttswrappers
    copying aeneas/ttswrappers/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/ttswrappers
    copying aeneas/ttswrappers/awsttswrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/ttswrappers
    copying aeneas/ttswrappers/basettswrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/ttswrappers
    copying aeneas/ttswrappers/espeakngttswrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/ttswrappers
    copying aeneas/ttswrappers/espeakttswrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/ttswrappers
    copying aeneas/ttswrappers/festivalttswrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/ttswrappers
    copying aeneas/ttswrappers/macosttswrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/ttswrappers
    copying aeneas/ttswrappers/nuancettswrapper.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/ttswrappers
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/res
    copying aeneas/res/__init__.py -> build/lib.macosx-10.11-x86_64-3.6/aeneas/res
    copying aeneas/res/finetuneas.html -> build/lib.macosx-10.11-x86_64-3.6/aeneas/res
    copying aeneas/res/LiberationMono-Regular.ttf -> build/lib.macosx-10.11-x86_64-3.6/aeneas/res
    copying aeneas/README.md -> build/lib.macosx-10.11-x86_64-3.6/aeneas
    copying aeneas/cdtw/cdtw_driver.c -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cdtw
    copying aeneas/cdtw/cdtw_func.c -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cdtw
    copying aeneas/cdtw/cdtw_py.c -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cdtw
    copying aeneas/cdtw/cdtw_func.h -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cdtw
    copying aeneas/cdtw/README.md -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cdtw
    copying aeneas/cew/cew_func.h -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cew
    copying aeneas/cew/speak_lib.h -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cew
    copying aeneas/cew/README.md -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cew
    copying aeneas/cmfcc/cmfcc_driver.c -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cmfcc
    copying aeneas/cmfcc/cmfcc_func.c -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cmfcc
    copying aeneas/cmfcc/cmfcc_py.c -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cmfcc
    copying aeneas/cmfcc/cmfcc_func.h -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cmfcc
    copying aeneas/cmfcc/README.md -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cmfcc
    copying aeneas/cwave/cwave_driver.c -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cwave
    copying aeneas/cwave/cwave_func.c -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cwave
    copying aeneas/cwave/cwave_py.c -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cwave
    copying aeneas/cwave/cwave_func.h -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cwave
    copying aeneas/cwave/README.md -> build/lib.macosx-10.11-x86_64-3.6/aeneas/cwave
    copying aeneas/extra/README.md -> build/lib.macosx-10.11-x86_64-3.6/aeneas/extra
    creating build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/audio.mp3 -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/audio.wav -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/config.bad.txt -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/config.bad.xml -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/config.txt -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/config.xml -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/job.bad.zip -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/job.zip -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/job_no_config.zip -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/mplain.txt -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/munparsed.xhtml -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/munparsed2.xhtml -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/page.xhtml -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/parsed.txt -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/plain.txt -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/sonnet.csv -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/sonnet.json -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/sonnet.vad -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/sonnet.zzz -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/subtitles.txt -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/unparsed.xhtml -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/res/words.txt -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools/res
    copying aeneas/tools/README.md -> build/lib.macosx-10.11-x86_64-3.6/aeneas/tools
    copying aeneas/ttswrappers/README.md -> build/lib.macosx-10.11-x86_64-3.6/aeneas/ttswrappers
    running build_ext
    building 'aeneas.cdtw.cdtw' extension
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
    
    creating build/temp.macosx-10.11-x86_64-3.6
    creating build/temp.macosx-10.11-x86_64-3.6/aeneas
    creating build/temp.macosx-10.11-x86_64-3.6/aeneas/cdtw
    creating build/temp.macosx-10.11-x86_64-3.6/aeneas/cint
    compile options: '-I/usr/local/lib/python3.6/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c'
    clang: aeneas/cdtw/cdtw_py.c
    clang: aeneas/cdtw/cdtw_func.c
    clang: aeneas/cint/cint.c
    clang -bundle -undefined dynamic_lookup build/temp.macosx-10.11-x86_64-3.6/aeneas/cdtw/cdtw_py.o build/temp.macosx-10.11-x86_64-3.6/aeneas/cdtw/cdtw_func.o build/temp.macosx-10.11-x86_64-3.6/aeneas/cint/cint.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.11-x86_64-3.6/aeneas/cdtw/cdtw.cpython-36m-darwin.so
    building 'aeneas.cmfcc.cmfcc' extension
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
    
    creating build/temp.macosx-10.11-x86_64-3.6/aeneas/cmfcc
    creating build/temp.macosx-10.11-x86_64-3.6/aeneas/cwave
    compile options: '-I/usr/local/lib/python3.6/site-packages/numpy/core/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c'
    clang: aeneas/cmfcc/cmfcc_py.c
    clang: aeneas/cmfcc/cmfcc_func.c
    aeneas/cmfcc/cmfcc_func.c:83:19: warning: comparison of integers of different signs: 'int' and 'const uint32_t' (aka 'const unsigned int') [-Wsign-compare]
        for (k = 1; k < size; ++k) {
                    ~ ^ ~~~~
    aeneas/cmfcc/cmfcc_func.c:109:31: warning: comparison of integers of different signs: 'int' and 'const uint32_t' (aka 'const unsigned int') [-Wsign-compare]
                for (li = lix; li <= m; li += lix) {
                               ~~ ^  ~
    2 warnings generated.
    clang: aeneas/cwave/cwave_func.c
    clang -bundle -undefined dynamic_lookup build/temp.macosx-10.11-x86_64-3.6/aeneas/cmfcc/cmfcc_py.o build/temp.macosx-10.11-x86_64-3.6/aeneas/cmfcc/cmfcc_func.o build/temp.macosx-10.11-x86_64-3.6/aeneas/cwave/cwave_func.o build/temp.macosx-10.11-x86_64-3.6/aeneas/cint/cint.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.11-x86_64-3.6/aeneas/cmfcc/cmfcc.cpython-36m-darwin.so
    building 'aeneas.cew.cew' extension
    C compiler: clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes
    
    creating build/temp.macosx-10.11-x86_64-3.6/aeneas/cew
    compile options: '-I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c'
    clang: aeneas/cew/cew_py.c
    clang: aeneas/cew/cew_func.c
    clang -bundle -undefined dynamic_lookup build/temp.macosx-10.11-x86_64-3.6/aeneas/cew/cew_py.o build/temp.macosx-10.11-x86_64-3.6/aeneas/cew/cew_func.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lespeak -o build/lib.macosx-10.11-x86_64-3.6/aeneas/cew/cew.cpython-36m-darwin.so
    ld: library not found for -lespeak
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ld: library not found for -lespeak
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    error: Command "clang -bundle -undefined dynamic_lookup build/temp.macosx-10.11-x86_64-3.6/aeneas/cew/cew_py.o build/temp.macosx-10.11-x86_64-3.6/aeneas/cew/cew_func.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lespeak -o build/lib.macosx-10.11-x86_64-3.6/aeneas/cew/cew.cpython-36m-darwin.so" failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python3/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/var/folders/xb/g15nz0cs7454zz7hcj8lp2v80000gn/T/pip-build-uobew6o9/aeneas/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/xb/g15nz0cs7454zz7hcj8lp2v80000gn/T/pip-42yuuttg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/xb/g15nz0cs7454zz7hcj8lp2v80000gn/T/pip-build-uobew6o9/aeneas/

**Comment by pettarin** [comment]
The error is the following:

ld: library not found for -lespeak

(at the very end of your log), meaning that the compiler cannot find the 
espeak header files to build the cew C extension.

Please refer to the Mac OS X directions:

  https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md#mac-os-x

you probably want to install via brew.

HTH,

AP
