### ISSUE TITLE
how to add confidence for each aligned word ?

### ISSUE THREAD

**Issue by superhg2012** [readbeyond/aeneas#197]
Hi,  I want to add confidence for each word aligned in the output syncmap json file like below:

{
 "fragments": [
  {
   "begin": "0.000",
   "children": [],
   "end": "1.520",
   "id": "f000001",
   "language": "eng",
   "confidence": "0.8"
   "lines": [
    "good"
   ]
  },
  {
   "begin": "1.520",
   "children": [],
   "end": "3.160",
   "id": "f000002",
   "language": "eng",
   "confidence": "0.6"
   "lines": [
    "morning"
   ]
  },
....
}

the confidence field means the best dtw aligned result(or best similarity or probability ranging 0 ~ 1) for words in  text to be aligned, it should be computed from the dtw aligner.
how can I get the confidence value?

**Comment by readbeyond** [comment]
On 01/31/2018 07:31 AM, Gang He wrote:
> the confidence field means the best dtw aligned result(or best 
> similarity) for words in text to be aligned,

First of all, the above is not a well-defined description (in the 
mathematical sense) of the value you are looking for. Please read 
https://github.com/readbeyond/aeneas/blob/master/wiki/HOWITWORKS.md to 
learn how aeneas computes the forced alignment.

Then, please read the first messages of this thread in the mailing list:

https://groups.google.com/forum/#!topic/aeneas-forced-alignment/gQKpbhbX7Lw

(Unfortunately several topics got mixed in the same thread linked above, 
but the first messages do contain some discussion about the 
error/confidence/score.)

In short, I do not see a sound way of estimating the 
error/score/confidence, without changing the algorithmic approach of 
aeneas towards what ASR-based system do (i.e., without relying on big 
language models, incorporating both orthography and phonology 
information). And I really do not want to go that way: if you prefer 
those approaches, there are several aligners out there, many open source 
and/or freeware and/or free software. See 
https://github.com/pettarin/forced-alignment-tools

Maybe in aeneas 2.x I might have the DTW code to compute such an 
error/score/confidence value, computed e.g. by looking at the costs of 
the alignment path, or later e.g. looking at the spectral features or 
speech/non-speech trajectories of the intervals found versus the text 
they are associated to, but as I said above, at the moment I do not see 
a precise way of defining what this score would be, given the current 
algorithm strategy.

AP

**Comment by superhg2012** [comment]
@readbeyond sorry for the terrible description for my question. I saw the discussion in the mailing list. it's exactly my question and I do need an approach to estimate the accuracy of the sync maps output by aeneas . 

Thanks for your reply and I am looking for the aeneas 2.x
