### ISSUE TITLE
Cant install espeak

### ISSUE THREAD

**Issue by anshallad97** [readbeyond/aeneas#198]
First of all thank you so much for your work. My issue is as follows -
Setup for windows provided by espeak (link given by you in description) cant be downloaded and installed.
Can u please provide espeak setup ?
My system running on windows 10 (x64) .

**Comment by readbeyond** [comment]
Please follow the directions in:

https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md#windows

I am able to download the all-in-one installer from:

https://github.com/sillsdev/aeneas-installer/releases

or just eSpeak from:

http://espeak.sourceforge.net/download.html

HTH,

AP

**Comment by anshallad97** [comment]
Thanks , will try this for sure.
