### ISSUE TITLE
[Question] How to force align when (speech) audio contains only a subset of transcription text file

### ISSUE THREAD

**Issue by vinaywadhwa** [readbeyond/aeneas#208]
Example :
Transcription text file - 10,000 lines
10 audio files - variable duration.. every audio file contains about 800-1200 lines of speech from the transcript file. 

I tried running the aligner with the complete 10,000 lines text file with about 800-1200 lines speech audio file, doesn't work, as i expected. 

How would i go about extracting and aligning text from this file using Aenas? (I don't want to do it manually by listening to the audio files and splitting the transcript text into 10). 

Apologies, if this is not completely related to Aenas functioning. Or maybe it is? Any help or direction to solve this problem would be appreciated.

**Comment by readbeyond** [comment]
Hi,

if the ratio between "to be aligned" and "other text" is roughly 1:9, 
the algorithmic approach of aeneas is simply not good for the problem.

BTW, if you "only" have 10 fragments, it takes you 10 minutes to listen 
to the begin/end of each audio file, find the corresponding line in the 
text file, and split the text accordingly, so you can run a 1:1 task in 
aeneas. This is probably still much faster that having to align 
manually. Why is this not feasible? Do you have N >> 1 such jobs to run?

Best regards,

Alberto Pettarin

**Comment by vinaywadhwa** [comment]
>> the algorithmic approach of aeneas is simply not good for the problem.
 - Got it. Thanks for your reply.
