### ISSUE TITLE
Prune Debian dependencies in install_dependencies.sh

### ISSUE THREAD

**Issue by pettarin** [readbeyond/aeneas#21]
Possibly, in a way compatible with `aeneas-vagrant`

**Comment by chrisvire** [comment]
Also, "apt-get install -y espeak*" selects too many packages.  I was able to build with this list:

apt-get install -y espeak espeak-data libespeak-dev libespeak1

I am not sure that espeak-data is required in the list.

**Comment by readbeyond** [comment]
On 10/26/2015 10:03 PM, Chris Hubbard wrote:
> Also, "apt-get install -y espeak*" selects too many packages. I was able
> to build with this list:
>
> apt-get install -y espeak espeak-data libespeak-dev libespeak1
>
> I am not sure that espeak-data is required in the list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/readbeyond/aeneas/issues/21#issuecomment-151284202>.
>

espeak-data is required, as it contains the voice files (dictionaries, 
phonemes, etc.) for espeak

**Comment by readbeyond** [comment]
Done in v1.3.1. Closing.
