### ISSUE TITLE
 Both the C extension and the pure Python code failed. (Wrong arguments? Input too big?)

### ISSUE THREAD

**Issue by Lakshyasukhralia** [readbeyond/aeneas#213]
**Getting the following error:**
[ERRO] An unexpected error occurred while executing the task:
[ERRO] Unexpected error while executing task : Both the C extension and the pure Python code failed. (Wrong arguments? Input too big?)

**Input Command :** 
python -m aeneas.tools.execute_task venom.mp3 lyrics.txt "task_language=en|is_text_type=plain|os_task_file_format=srt" subs.srt

**venom.mp3:**
Type = .mp3
Length = 4:07 min

**lyrics.txt Format:**
Encoding = UTF-8
Lines = 116
Content = 
I got a song filled with shit for the strong-willed
When the world gives you a raw deal
Set you off till you scream, "Piss off! Screw you!"
When it talks to you like you don't belong
Or tells you you're in the wrong field
When's something's in your mitochondrial
'Cause it latched on to you, like-

Knock knock, let the devil in
Malevolent as I've ever been, head is spinnin'
This medicine's screamin', "L-l-l-let us in!"
L-l-lick like a salad bowl, Edgar Allen Poe
Bedridden, shoulda been dead a long time ago
Liquid Tylenol, gelatins, think my skeleton's meltin'
Wicked, I get all high when I think I've smelled the scent
Of elephant manure-hell, I meant Kahlúa

**Log:**
[tmpbjahhmav.log](https://github.com/readbeyond/aeneas/files/2351192/tmpbjahhmav.log)

**Any help would be appreciated.
Thanks for your amazing work with this software!**

**Note***
Tried using mplain too but same result

**Comment by Lakshyasukhralia** [comment]
@readbeyond Thanks a lot. Worked like a charm!

**Comment by ArvinderKumar** [comment]
I am also stuck with same error. Have attached audio and text downloaded from aeneas tutorial. 
[text.txt](https://github.com/readbeyond/aeneas/files/2976562/text.txt)

Have tried with several other audios and text but all have similar issue. Could you pls. check and help. Don't have BOM issue at my end.

**Comment by ArvinderKumar** [comment]
[p001.zip](https://github.com/readbeyond/aeneas/files/2976565/p001.zip)

**Comment by ArvinderKumar** [comment]
have installed python 3.6. FFprobe and FFmpeg are perfectly installed.

**Comment by readbeyond** [comment]
What platform are you working on?

Please note that e.g. there are know installation issues / limitations 
running aeneas on Windows. Only Linux 64 bit is officially supported. 
See: https://github.com/readbeyond/aeneas/#supported-platforms

In particular, if you get the "Both the C extension and the pure Python 
code failed." error, it is likely you do not have aeneas installed 
correctly. What is the output of:

$ python -m aeneas.diagnostics

?

If you only need to process a few audio/text pairs, you can use the 
aeneas Web application: https://www.aeneasweb.org/

Best regards,

Alberto Pettarin

**Comment by ArvinderKumar** [comment]
Thanks Alberto for a quick reply:
Here's the result of diagnostics:
D:\test>python -m aeneas.diagnostics
[INFO] ffprobe        OK[INFO] ffmpeg         OK[ERRO] espeak         ERROR[INFO]   Please make sure you have espeak installed correctly[INFO]   and that its path is in your PATH environment variable[INFO]   You might also want to check that the espeak-data directory[INFO]   is set up correctly, for example, it has the correct permissions

BTW, I create read aloud e-books, where i map human recorded voice with its text and use audicity tool to get the audio timings which is a complete manual and time consuming process.
I want to automate this manual process and if i get exact timings of audios of different human voices which i can map to its text then that would be of great help. I found your aeneas library can do wonder for this.
Regards,Arvinder



    On Tuesday, March 19, 2019, 2:00:14 AM GMT+5:30, ReadBeyond <notifications@github.com> wrote:  
 
 What platform are you working on?

Please note that e.g. there are know installation issues / limitations 
running aeneas on Windows. Only Linux 64 bit is officially supported. 
See: https://github.com/readbeyond/aeneas/#supported-platforms

In particular, if you get the "Both the C extension and the pure Python 
code failed." error, it is likely you do not have aeneas installed 
correctly. What is the output of:

$ python -m aeneas.diagnostics

?

If you only need to process a few audio/text pairs, you can use the 
aeneas Web application: https://www.aeneasweb.org/

Best regards,

Alberto Pettarin

**Comment by pettarin** [comment]
The diagnostics clearly shows that:

1. aeneas seems installed correctly
2. espeak is not in your PATH

You should add the directory containing the espeak.exe executable to 
your PATH environment variable.

See: 
https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md#windows

How did you install aeneas? Again, please note that it is not officially 
supported on Windows. The installer package and directions were provided 
by Daniel Bair / SIL.

Best regards,

Alberto Pettarin
