### ISSUE TITLE
Error: Unable to create file 'output/sonnet.words.aud'

### ISSUE THREAD

**Issue by jarodtang** [readbeyond/aeneas#216]
I was trying to enable mfcc by following command, but failed, could you tell how to fix?

> python -m aeneas.tools.execute_task --example-words --presets-word  tlp/c4.mp3 tlp/ch4.mplain "task_language=eng|os_task_file_format=srt|is_text_type=plain" tlp/ch4.srt
> [INFO] Preset for word-level alignment
> [ERRO] Unable to create file 'output/sonnet.words.aud'
> [ERRO] Make sure the file path is written/escaped correctly and that you have write permission on it
>

**Comment by jarodtang** [comment]
>  python -m aeneas.diagnostics
> [INFO] ffprobe        OK
> [INFO] ffmpeg         OK
> [INFO] espeak         OK
> [INFO] aeneas.tools   OK
> [INFO] shell encoding OK
> RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
> [WARN] aeneas.cdtw    NOT AVAILABLE
> [INFO]   You can still run aeneas but it will be significantly slower
> [INFO]   Please refer to the installation documentation for details
> RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
> [WARN] aeneas.cmfcc   NOT AVAILABLE
> [INFO]   You can still run aeneas but it will be significantly slower
> [INFO]   Please refer to the installation documentation for details
> [INFO] aeneas.cew     AVAILABLE
> [WARN] All required dependencies are met but at least one Python C extension is not available

**Comment by readbeyond** [comment]
Hi, first of all, if you use "--example-words", it will run the built-in input files of that example, not your input files, so you probably want to remove "--example-words" from your command line.

The error "unable to create file ..." probably means that you do not have a directory "output" as child of your current working directory. As noted above, "output/sonnet.words.aud" is the sync map output file of the built-in example "--example-words".

**Comment by jarodtang** [comment]
thanks, got it
