### ISSUE TITLE
Not able to install aeneas in Ubuntu 14.04 using pip

### ISSUE THREAD

**Issue by vaibhav1406** [readbeyond/aeneas#220]
When I run `sudo pip install aeneas`, I'm getting the below mentioned error:

  creating build/temp.linux-x86_64-2.7/aeneas/cew
  compile options: '-I['/usr/local/lib/python2.7/dist-packages/numpy/core/include'] -I/usr/include/python2.7 -c'
  x86_64-linux-gnu-gcc: aeneas/cew/cew_func.c
  x86_64-linux-gnu-gcc: aeneas/cew/cew_py.c
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/aeneas/cew/cew_py.o build/temp.linux-x86_64-2.7/aeneas**/cew/cew_func.o -lespeak -o build/lib.linux-x86_64-2.7/aeneas/cew/cew.so
  **/usr/bin/ld: cannot find -lespeak
  collect2: error: ld returned 1 exit status
  /usr/bin/ld: cannot find -lespeak
  collect2: error: ld returned 1 exit status****
  error: Command "x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/aeneas/cew/cew_py.o build/temp.linux-x86_64-2.7/aeneas/cew/cew_func.o -lespeak -o build/lib.linux-x86_64-2.7/aeneas/cew/cew.so" failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for aeneas

**Comment by readbeyond** [comment]
You do not have the espeak headers installed.

Please read:

https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md

I guess you need to apt-get install libespeak-dev first. You can also 
use the install_dependencies.sh script: it was tested on Debian, but it 
should work for Ubuntu as well.

Best regards,

Alberto Pettarin

**Comment by vaibhav1406** [comment]
Yes, it worked after running install_dependencies.sh script.

Thankyou @readbeyond
