### ISSUE TITLE
Error with pip install aeneas

### ISSUE THREAD

**Issue by gamel2018** [readbeyond/aeneas#221]
I tried to install aeneas on Windows 10 following the instruction in the Readme file and failed.  Following are the errors.  Any idea?

C:\Users\V>python --version
Python 2.7.15

C:\Users\V>pip install aeneas
Collecting aeneas
  Using cached https://files.pythonhosted.org/packages/e5/92/88d421001bb257588df4864ceca24d570e2e822db4f40f48737a78b648b2/aeneas-1.7.3.0.tar.gz
Requirement already satisfied: BeautifulSoup4>=4.5.1 in c:\python27\lib\site-packages (from aeneas)
Requirement already satisfied: lxml>=3.6.0 in c:\python27\lib\site-packages (from aeneas)
Requirement already satisfied: numpy>=1.9 in c:\python27\lib\site-packages (from aeneas)
Installing collected packages: aeneas
  Running setup.py install for aeneas ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\v\\appdata\\local\\temp\\pip-build-lwzsah\\aeneas\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\v\appdata\local\temp\pip-nc5atr-record\install-record.txt --single-version-externally-managed --compile:
    [INFO] *****************************************************************
    [INFO] Compiling the C extension cew on Windows is experimental.
    [INFO]
    [INFO] If you experience problems, disable cew compilation by specifying
    [INFO] the environment variable AENEAS_WITH_CEW=False .
    [INFO] Please see the aeneas installation documentation for details.
    [INFO] *****************************************************************
    [INFO]
    [INFO] Found eSpeak DLL in aeneas\cew\espeak.dll
    [INFO] Found eSpeak LIB in c:\users\v\appdata\local\temp\pip-build-lwzsah\aeneas\espeak.lib
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\aeneas
    copying aeneas\adjustboundaryalgorithm.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\analyzecontainer.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\audiofile.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\audiofilemfcc.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\cewsubprocess.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\configuration.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\container.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\diagnostics.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\downloader.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\dtw.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\exacttiming.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\executejob.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\executetask.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\ffmpegwrapper.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\ffprobewrapper.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\globalconstants.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\globalfunctions.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\hierarchytype.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\idsortingalgorithm.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\job.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\language.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\logger.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\mfcc.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\plotter.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\runtimeconfiguration.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\sd.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\synthesizer.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\task.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\textfile.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\tree.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\vad.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\validator.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\wavfile.py -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\__init__.py -> build\lib.win-amd64-2.7\aeneas
    creating build\lib.win-amd64-2.7\aeneas\cdtw
    copying aeneas\cdtw\cdtw_setup.py -> build\lib.win-amd64-2.7\aeneas\cdtw
    copying aeneas\cdtw\__init__.py -> build\lib.win-amd64-2.7\aeneas\cdtw
    creating build\lib.win-amd64-2.7\aeneas\cew
    copying aeneas\cew\cew_setup.py -> build\lib.win-amd64-2.7\aeneas\cew
    copying aeneas\cew\__init__.py -> build\lib.win-amd64-2.7\aeneas\cew
    creating build\lib.win-amd64-2.7\aeneas\cfw
    copying aeneas\cfw\cfw_setup.py -> build\lib.win-amd64-2.7\aeneas\cfw
    copying aeneas\cfw\__init__.py -> build\lib.win-amd64-2.7\aeneas\cfw
    creating build\lib.win-amd64-2.7\aeneas\cmfcc
    copying aeneas\cmfcc\cmfcc_setup.py -> build\lib.win-amd64-2.7\aeneas\cmfcc
    copying aeneas\cmfcc\__init__.py -> build\lib.win-amd64-2.7\aeneas\cmfcc
    creating build\lib.win-amd64-2.7\aeneas\cwave
    copying aeneas\cwave\cwave_setup.py -> build\lib.win-amd64-2.7\aeneas\cwave
    copying aeneas\cwave\__init__.py -> build\lib.win-amd64-2.7\aeneas\cwave
    creating build\lib.win-amd64-2.7\aeneas\extra
    copying aeneas\extra\ctw_espeak.py -> build\lib.win-amd64-2.7\aeneas\extra
    copying aeneas\extra\ctw_speect.py -> build\lib.win-amd64-2.7\aeneas\extra
    copying aeneas\extra\__init__.py -> build\lib.win-amd64-2.7\aeneas\extra
    creating build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\format.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\fragment.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\fragmentlist.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\headtailformat.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\missingparametererror.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfaudacity.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfbase.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfcsv.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfeaf.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfgsubtitles.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfgtabular.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfgxml.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfjson.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfrbse.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfsmil.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfsrt.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfssv.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfsub.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smftextgrid.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smftsv.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfttml.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smftxt.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfvtt.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfxml.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\smfxmllegacy.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    copying aeneas\syncmap\__init__.py -> build\lib.win-amd64-2.7\aeneas\syncmap
    creating build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\abstract_cli_program.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\convert_syncmap.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\download.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\execute_job.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\execute_task.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\extract_mfcc.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\ffmpeg_wrapper.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\ffprobe_wrapper.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\hydra.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\plot_waveform.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\read_audio.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\read_text.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\run_sd.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\run_vad.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\synthesize_text.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\validate.py -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\tools\__init__.py -> build\lib.win-amd64-2.7\aeneas\tools
    creating build\lib.win-amd64-2.7\aeneas\ttswrappers
    copying aeneas\ttswrappers\awsttswrapper.py -> build\lib.win-amd64-2.7\aeneas\ttswrappers
    copying aeneas\ttswrappers\basettswrapper.py -> build\lib.win-amd64-2.7\aeneas\ttswrappers
    copying aeneas\ttswrappers\espeakngttswrapper.py -> build\lib.win-amd64-2.7\aeneas\ttswrappers
    copying aeneas\ttswrappers\espeakttswrapper.py -> build\lib.win-amd64-2.7\aeneas\ttswrappers
    copying aeneas\ttswrappers\festivalttswrapper.py -> build\lib.win-amd64-2.7\aeneas\ttswrappers
    copying aeneas\ttswrappers\macosttswrapper.py -> build\lib.win-amd64-2.7\aeneas\ttswrappers
    copying aeneas\ttswrappers\nuancettswrapper.py -> build\lib.win-amd64-2.7\aeneas\ttswrappers
    copying aeneas\ttswrappers\__init__.py -> build\lib.win-amd64-2.7\aeneas\ttswrappers
    creating build\lib.win-amd64-2.7\aeneas\res
    copying aeneas\res\finetuneas.html -> build\lib.win-amd64-2.7\aeneas\res
    copying aeneas\res\LiberationMono-Regular.ttf -> build\lib.win-amd64-2.7\aeneas\res
    copying aeneas\res\__init__.py -> build\lib.win-amd64-2.7\aeneas\res
    copying aeneas\README.md -> build\lib.win-amd64-2.7\aeneas
    copying aeneas\cdtw\cdtw_driver.c -> build\lib.win-amd64-2.7\aeneas\cdtw
    copying aeneas\cdtw\cdtw_func.c -> build\lib.win-amd64-2.7\aeneas\cdtw
    copying aeneas\cdtw\cdtw_py.c -> build\lib.win-amd64-2.7\aeneas\cdtw
    copying aeneas\cdtw\cdtw_func.h -> build\lib.win-amd64-2.7\aeneas\cdtw
    copying aeneas\cdtw\README.md -> build\lib.win-amd64-2.7\aeneas\cdtw
    copying aeneas\cew\cew_func.h -> build\lib.win-amd64-2.7\aeneas\cew
    copying aeneas\cew\speak_lib.h -> build\lib.win-amd64-2.7\aeneas\cew
    copying aeneas\cew\README.md -> build\lib.win-amd64-2.7\aeneas\cew
    copying aeneas\cmfcc\cmfcc_driver.c -> build\lib.win-amd64-2.7\aeneas\cmfcc
    copying aeneas\cmfcc\cmfcc_func.c -> build\lib.win-amd64-2.7\aeneas\cmfcc
    copying aeneas\cmfcc\cmfcc_py.c -> build\lib.win-amd64-2.7\aeneas\cmfcc
    copying aeneas\cmfcc\cmfcc_func.h -> build\lib.win-amd64-2.7\aeneas\cmfcc
    copying aeneas\cmfcc\README.md -> build\lib.win-amd64-2.7\aeneas\cmfcc
    copying aeneas\cwave\cwave_driver.c -> build\lib.win-amd64-2.7\aeneas\cwave
    copying aeneas\cwave\cwave_func.c -> build\lib.win-amd64-2.7\aeneas\cwave
    copying aeneas\cwave\cwave_py.c -> build\lib.win-amd64-2.7\aeneas\cwave
    copying aeneas\cwave\cwave_func.h -> build\lib.win-amd64-2.7\aeneas\cwave
    copying aeneas\cwave\README.md -> build\lib.win-amd64-2.7\aeneas\cwave
    copying aeneas\extra\README.md -> build\lib.win-amd64-2.7\aeneas\extra
    creating build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\audio.mp3 -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\audio.wav -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\config.bad.txt -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\config.bad.xml -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\config.txt -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\config.xml -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\job.bad.zip -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\job.zip -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\job_no_config.zip -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\mplain.txt -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\munparsed.xhtml -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\munparsed2.xhtml -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\page.xhtml -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\parsed.txt -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\plain.txt -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\sonnet.csv -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\sonnet.json -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\sonnet.vad -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\sonnet.zzz -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\subtitles.txt -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\unparsed.xhtml -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\res\words.txt -> build\lib.win-amd64-2.7\aeneas\tools\res
    copying aeneas\tools\README.md -> build\lib.win-amd64-2.7\aeneas\tools
    copying aeneas\ttswrappers\README.md -> build\lib.win-amd64-2.7\aeneas\ttswrappers
    running build_ext
    building 'aeneas.cdtw.cdtw' extension
    creating build\temp.win-amd64-2.7
    creating build\temp.win-amd64-2.7\Release
    creating build\temp.win-amd64-2.7\Release\aeneas
    creating build\temp.win-amd64-2.7\Release\aeneas\cdtw
    creating build\temp.win-amd64-2.7\Release\aeneas\cint
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\lib\site-packages\numpy\core\include -I['c:\\python27\\lib\\site-packages\\numpy\\core\\include'] -Ic:\python27\include -Ic:\python27\PC /Tcaeneas/cdtw/cdtw_py.c /Fobuild\temp.win-amd64-2.7\Release\aeneas/cdtw/cdtw_py.obj
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\lib\site-packages\numpy\core\include -I['c:\\python27\\lib\\site-packages\\numpy\\core\\include'] -Ic:\python27\include -Ic:\python27\PC /Tcaeneas/cdtw/cdtw_func.c /Fobuild\temp.win-amd64-2.7\Release\aeneas/cdtw/cdtw_func.obj
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\lib\site-packages\numpy\core\include -I['c:\\python27\\lib\\site-packages\\numpy\\core\\include'] -Ic:\python27\include -Ic:\python27\PC /Tcaeneas/cint/cint.c /Fobuild\temp.win-amd64-2.7\Release\aeneas/cint/cint.obj
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:c:\python27\libs /LIBPATH:c:\python27\PCbuild\amd64 /LIBPATH:c:\python27\PC\VS9.0\amd64 /EXPORT:initcdtw build\temp.win-amd64-2.7\Release\aeneas/cdtw/cdtw_py.obj build\temp.win-amd64-2.7\Release\aeneas/cdtw/cdtw_func.obj build\temp.win-amd64-2.7\Release\aeneas/cint/cint.obj /OUT:build\lib.win-amd64-2.7\aeneas\cdtw\cdtw.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\aeneas/cdtw\cdtw.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\aeneas/cdtw\cdtw.pyd.manifest
    building 'aeneas.cmfcc.cmfcc' extension
    creating build\temp.win-amd64-2.7\Release\aeneas\cmfcc
    creating build\temp.win-amd64-2.7\Release\aeneas\cwave
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\lib\site-packages\numpy\core\include -I['c:\\python27\\lib\\site-packages\\numpy\\core\\include'] -Ic:\python27\include -Ic:\python27\PC /Tcaeneas/cmfcc/cmfcc_py.c /Fobuild\temp.win-amd64-2.7\Release\aeneas/cmfcc/cmfcc_py.obj
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\lib\site-packages\numpy\core\include -I['c:\\python27\\lib\\site-packages\\numpy\\core\\include'] -Ic:\python27\include -Ic:\python27\PC /Tcaeneas/cmfcc/cmfcc_func.c /Fobuild\temp.win-amd64-2.7\Release\aeneas/cmfcc/cmfcc_func.obj
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\lib\site-packages\numpy\core\include -I['c:\\python27\\lib\\site-packages\\numpy\\core\\include'] -Ic:\python27\include -Ic:\python27\PC /Tcaeneas/cwave/cwave_func.c /Fobuild\temp.win-amd64-2.7\Release\aeneas/cwave/cwave_func.obj
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\lib\site-packages\numpy\core\include -I['c:\\python27\\lib\\site-packages\\numpy\\core\\include'] -Ic:\python27\include -Ic:\python27\PC /Tcaeneas/cint/cint.c /Fobuild\temp.win-amd64-2.7\Release\aeneas/cint/cint.obj
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:c:\python27\libs /LIBPATH:c:\python27\PCbuild\amd64 /LIBPATH:c:\python27\PC\VS9.0\amd64 /EXPORT:initcmfcc build\temp.win-amd64-2.7\Release\aeneas/cmfcc/cmfcc_py.obj build\temp.win-amd64-2.7\Release\aeneas/cmfcc/cmfcc_func.obj build\temp.win-amd64-2.7\Release\aeneas/cwave/cwave_func.obj build\temp.win-amd64-2.7\Release\aeneas/cint/cint.obj /OUT:build\lib.win-amd64-2.7\aeneas\cmfcc\cmfcc.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\aeneas/cmfcc\cmfcc.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\aeneas/cmfcc\cmfcc.pyd.manifest
    building 'aeneas.cew.cew' extension
    creating build\temp.win-amd64-2.7\Release\aeneas\cew
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I['c:\\python27\\lib\\site-packages\\numpy\\core\\include'] -Ic:\python27\include -Ic:\python27\PC /Tcaeneas/cew/cew_py.c /Fobuild\temp.win-amd64-2.7\Release\aeneas/cew/cew_py.obj
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -I['c:\\python27\\lib\\site-packages\\numpy\\core\\include'] -Ic:\python27\include -Ic:\python27\PC /Tcaeneas/cew/cew_func.c /Fobuild\temp.win-amd64-2.7\Release\aeneas/cew/cew_func.obj
    C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:c:\python27\libs /LIBPATH:c:\python27\PCbuild\amd64 /LIBPATH:c:\python27\PC\VS9.0\amd64 espeak.lib /EXPORT:initcew build\temp.win-amd64-2.7\Release\aeneas/cew/cew_py.obj build\temp.win-amd64-2.7\Release\aeneas/cew/cew_func.obj /OUT:build\lib.win-amd64-2.7\aeneas\cew\cew.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\aeneas/cew\cew.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\aeneas/cew\cew.pyd.manifest
    cew_py.obj : warning LNK4197: export 'initcew' specified multiple times; using first specification
       Creating library build\temp.win-amd64-2.7\Release\aeneas/cew\cew.lib and object build\temp.win-amd64-2.7\Release\aeneas/cew\cew.exp
    cew_func.obj : error LNK2019: unresolved external symbol espeak_Terminate referenced in function _terminate_synthesis
    cew_func.obj : error LNK2019: unresolved external symbol espeak_Synchronize referenced in function _synthesize_string
    cew_func.obj : error LNK2019: unresolved external symbol espeak_Synth referenced in function _synthesize_string
    cew_func.obj : error LNK2019: unresolved external symbol espeak_SetVoiceByProperties referenced in function _set_voice_code
    cew_func.obj : error LNK2019: unresolved external symbol espeak_SetSynthCallback referenced in function _initialize_synthesizer
    cew_func.obj : error LNK2019: unresolved external symbol espeak_Initialize referenced in function _initialize_synthesizer
    build\lib.win-amd64-2.7\aeneas\cew\cew.pyd : fatal error LNK1120: 6 unresolved externals
    error: Command "C:\Users\V\AppData\Local\Programs\Common\Microsoft\Visual C++ for Python\9.0\VC\Bin\amd64\link.exe /DLL /nologo /INCREMENTAL:NO /LIBPATH:c:\python27\libs /LIBPATH:c:\python27\PCbuild\amd64 /LIBPATH:c:\python27\PC\VS9.0\amd64 espeak.lib /EXPORT:initcew build\temp.win-amd64-2.7\Release\aeneas/cew/cew_py.obj build\temp.win-amd64-2.7\Release\aeneas/cew/cew_func.obj /OUT:build\lib.win-amd64-2.7\aeneas\cew\cew.pyd /IMPLIB:build\temp.win-amd64-2.7\Release\aeneas/cew\cew.lib /MANIFESTFILE:build\temp.win-amd64-2.7\Release\aeneas/cew\cew.pyd.manifest" failed with exit status 1120

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\v\\appdata\\local\\temp\\pip-build-lwzsah\\aeneas\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\v\appdata\local\temp\pip-nc5atr-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\v\appdata\local\temp\pip-build-lwzsah\aeneas\
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by readbeyond** [comment]
cew_func.obj : error LNK2019: unresolved external symbol

pip is not able to find the eSpeak header files.

Please read:

https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md#installing-aeneas

https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md#windows

https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md#solving-errors-when-compiling-cew-1

but please be advised that installing on Windows has always been a pain 
in the back, your mileage might vary.

Best regards,

Alberto Pettarin

**Comment by jloguercio** [comment]
I got this error installing on ubuntu 18.04 , how can i solved it?

**Comment by readbeyond** [comment]
@jloguercio  Please read https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md and use the provided Bash script: https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md#manual-procedure

**Comment by bashkirtsevich** [comment]
(!) **Attention** for users with pyenv, `install_depths.sh` installing `python-dev` and `python-pip`
https://github.com/readbeyond/aeneas/blob/master/install_dependencies.sh#L64
