### ISSUE TITLE
Cannot set dtw algorithm to exact

### ISSUE THREAD

**Issue by tomassykora** [readbeyond/aeneas#225]
Hi,
I'm trying to find best parameters for our long audio files with long silence periods. I wanted to try exact dtw algorithm, but although I set `dtw_algorithm=exact`, the output during the process is always `Requested algorithm: 'stripe'`. Is it a bug or aren't my settings correct? This is the used python code:

```
config_string = u"task_language=eng|is_text_type=plain|os_task_file_format=json|dtw_algorithm=exact|mfcc_mask_nonspeech=True"
task = Task(config_string=config_string)
task.text_file = textfile

with tempfile.TemporaryDirectory() as tmp_dir:
    with tempfile.NamedTemporaryFile(dir=tmp_dir) as input_file, \
            tempfile.NamedTemporaryFile(dir=tmp_dir) as output_file:
        input_file.write(self.recording.audio('wav').read())
        task.audio_file_path_absolute = input_file.name
        task.sync_map_file_path_absolute = output_file.name

        aeneas_logger = Logger(tee=True)
        ExecuteTask(task, logger=aeneas_logger).execute()
        task.output_sync_map_file()
```

**Comment by readbeyond** [comment]
Hi,

you are mixing TaskConfiguration parameters and RuntimeConfiguration 
parameters.

In particular, "dtw_algorithm" and "mfcc_mask_nonspeech" are 
RuntimeConfiguration parameters.

In the command line:

python -m aeneas.tools.execute_task audio.mp3 text.txt 
"task_language=eng|is_text_type=subtitles|os_task_file_format=srt" 
output.srt -r="dtw_algorithm=exact|mfcc_mask_nonspeech=True"

If you add "-v" you will see the full log.

When using aeneas as a library, you might want to:

your_rconf = 
RuntimeConfiguration(config_string="dtw_algorithm=exact|mfcc_mask_nonspeech=True")

and then pass the rconf instance to e.g.

ExecuteTask(task=your_task, rconf=your_rconf, logger=your_logger)

or other methods that accept the rconf argument.

HTH,

Alberto Peettarin
