### ISSUE TITLE
Wrong timings (last 3 entries) on Windows 64/Python 2.7

### ISSUE THREAD

**Issue by mmeierer** [readbeyond/aeneas#227]
Thanks for creating and maintaining "aeneas"!

Unfortunately, I experienced some problems when trying to create SRT files: When running the SRT example 
`python -m aeneas.tools.execute_task --example-srt`
with Python 2.7 on Windows 10 (64bit), I get the output below. The last three entries seem to be wrongly timed. I experienced the same when I used my own audio files.

Is there a fix for this or is this a known issue?
 

1
00:00:00,000 --> 00:00:02,880
1

2
00:00:02,880 --> 00:00:07,280
From fairest creatures
we desire increase,

3
00:00:07,280 --> 00:00:11,600
That thereby beauty's rose
might never die,

4
00:00:11,600 --> 00:00:16,480
But as the riper
should by time decease,

5
00:00:16,480 --> 00:00:20,000
His tender heir
might bear his memory:

6
00:00:20,000 --> 00:00:24,480
But thou contracted
to thine own bright eyes,

7
00:00:24,480 --> 00:00:31,720
Feed'st thy light's flame
with self-substantial fuel,

8
00:00:31,720 --> 00:00:35,480
Making a famine
where abundance lies,

9
00:00:35,480 --> 00:00:41,800
Thy self thy foe,
to thy sweet self too cruel:

10
00:00:41,800 --> 00:00:47,400
Thou that art now
the world's fresh ornament,

11
00:00:47,400 --> 00:00:51,560
And only herald to the gaudy spring,

12
00:00:51,560 --> 00:00:53,200
Within thine own bud
buriest thy content,

13
**00:00:53,200 --> 00:00:53,200**
And tender churl mak'st waste in niggarding:

14
**00:00:53,200 --> 00:00:53,200**
Pity the world,
or else this glutton be,

15
**00:00:53,200 --> 00:00:53,240**
To eat the world's due,
by the grave and thee.

**Comment by mmeierer** [comment]
Following the advice in https://github.com/readbeyond/aeneas/issues/190, I've uninstalled 1.7.3 and installed 1.7.0. Now, I actually seems to work. 

Out of is now as follows:

1
00:00:00,000 --> 00:00:02,680
1

2
00:00:02,680 --> 00:00:05,840
From fairest creatures
we desire increase,

3
00:00:05,840 --> 00:00:09,240
That thereby beauty's rose
might never die,

4
00:00:09,240 --> 00:00:11,920
But as the riper
should by time decease,

5
00:00:11,920 --> 00:00:15,280
His tender heir
might bear his memory:

6
00:00:15,280 --> 00:00:18,600
But thou contracted
to thine own bright eyes,

7
00:00:18,600 --> 00:00:22,800
Feed'st thy light's flame
with self-substantial fuel,

8
00:00:22,800 --> 00:00:25,720
Making a famine
where abundance lies,

9
00:00:25,720 --> 00:00:31,240
Thy self thy foe,
to thy sweet self too cruel:

10
00:00:31,240 --> 00:00:34,280
Thou that art now
the world's fresh ornament,

11
00:00:34,280 --> 00:00:36,960
And only herald to the gaudy spring,

12
00:00:36,960 --> 00:00:40,640
Within thine own bud
buriest thy content,

**13
00:00:40,640 --> 00:00:44,480
And tender churl mak'st waste in niggarding:

14
00:00:44,480 --> 00:00:48,520
Pity the world,
or else this glutton be,

15
00:00:48,520 --> 00:00:53,240
To eat the world's due,
by the grave and thee.**

**Comment by readbeyond** [comment]
OK, thank you for letting me know.

I guess I really need to find time to debug on Windows and fix this 
regression...

AP
