### ISSUE TITLE
Tibetan Language Support

### ISSUE THREAD

**Issue by Joee1995** [readbeyond/aeneas#230]
Does Aeneas support Tibetan language? If not, is it possible to use custom data training model to support it? What should I do? Hope your help, and thx in advance!

**Comment by pettarin** [comment]
aeneas support any language that your TTS engine supports. None of the TTS drivers built-in aeneas support Tibetan, but if you find a TTS system that synthesizes Tibetan, you would need to write a simple driver, and specify the ``allow_unlisted_languages=True`` rconf parameter.

A quick Google research found only these two TTS supporting Tibetan, YMMV:

http://mary.dfki.de/documentation/tibetan.html 
http://www.eguidedog.net/ekho.php
