### ISSUE TITLE
Timings lag toward end on OSX

### ISSUE THREAD

**Issue by scriptorum** [readbeyond/aeneas#233]
Thanks for the awesome software! I'm doing word level timings, with recordings of several paragraphs -- about 250 words. I'm using multi level text format and Aeneas 1.73. I've tried eSpeak and eSpeak-NG. (I wanted to try Festival but I had troubles building it.)

Here's the issue: The first few paragraphs consistently exhibit very good timing, however as it gets to the last paragraph, the timing worsens, lagging behind by as much as half a second (the lag amount is inconsistent, but I speculate the more words the worse the lag).

I have tried tweaking a number of settings, but I'm currently using Aeneas as follows:

```code
 aeneas_execute_task "audio/<FILE>.mp3" text/<TRANSCRIPT>.txt 
  "is_text_type=mplain|
  is_audio_file_detect_head_min=0.5|
  is_audio_file_detect_head_max=1.5|
  os_task_file_format=json|
  os_task_file_levels=3|
  task_language=<LANG>|
  TTS='espeak-ng'|
  task_adjust_boundary_no_zero=True|
  task_adjust_boundary_nonspeech_min=0|
  task_adjust_boundary_algorithm=beforenext|
  task_adjust_boundary_beforenext_value=0.2" 
  map/<OUTPUT>.json 
  --presets-word 
  -r="mfcc_mask_nonspeech_l3=True"
```

Is there anything I might try? This may be related to #227, but I have not tested it on Windows to see if the lag is still there. I may try it with the Vagrant build.

**Comment by pettarin** [comment]
@scriptorum  I would need to try reproducing, can you send me your text and audio files privately (email here: https://www.albertopettarin.it/contact.html )? Can you try processing them with the aeneas Web app ( https://aeneasweb.org ) and see if it generates different out sync maps than your local installation? What OS / version of Python are you using?

**Comment by scriptorum** [comment]
I'm not seeing this issue any more. We since converted to running this on CentOS where it runs fine. When I tried to recreate the issue on OSX it's not lagging. 🙄  If I can dig up one of the older jobs that still demonstrates the issue, I'll reopen this ticket.
