### ISSUE TITLE
Technical description of method?

### ISSUE THREAD

**Issue by ftyers** [readbeyond/aeneas#236]
First of all, thanks for what looks like excellent software, I found out about it after reading [this overview](https://medium.com/@klintcho/creating-an-open-speech-recognition-dataset-for-almost-any-language-c532fb2bc0cf).

I'm curious how it works? I see TTS is a requirement, does that mean, that you convert the transcript to speech and then try and segment by aligning the lengths of the passages ? Or is it more complex ? I'd love to see a paper if there is one, or just a more technical writeup!

**Comment by chrisvaughn** [comment]
Alberto has a good write up here https://github.com/readbeyond/aeneas/blob/master/wiki/HOWITWORKS.md

**Comment by ftyers** [comment]
That's perfect, thanks! Perhaps a link to that could go in the main README.md? Sorry for cluttering up your issue tracker!

**Comment by chrisvaughn** [comment]
Agreed. It's linked from the main project site https://www.readbeyond.it/aeneas/ under documentation but a lot of people start from the repo.

**Comment by readbeyond** [comment]
Thanks to both.

The "how it works" document is also linked in the main readme.md, in 
section "Documentation and Support":

https://github.com/readbeyond/aeneas/#documentation-and-support

AP
