### ISSUE TITLE
libespeak-dev dep missing

### ISSUE THREAD

**Issue by stas00** [readbeyond/aeneas#238]
At least on ubuntu the requirements aren't just `espeak`, but `libespeak-dev` too.

I was getting `ld: cannot find -lespeak` w/o it during pip build. After `apt install libespeak-dev` I was able to successfully build aeneas.

Thank you!

**Comment by pettarin** [comment]
I think this has been discussed several times already, and the provided Bash scripts indeed installs ``libespeak-dev``:

https://github.com/readbeyond/aeneas/blob/master/install_dependencies.sh#L53

**Comment by stas00** [comment]
Thank you.

FWIW, it's only mentioned in the "manual install" section, which I wasn't following, I followed the pip install and it wasn't mentioned there. So if new users like myself repeatedly stumble here, perhaps mentioning that dependencies script installer in the pip installing section will make it clear for all.

**Comment by neymarsabin** [comment]
saved my day, thanks :+1:
