### ISSUE TITLE
run the example have a  different output json

### ISSUE THREAD

**Issue by sz-sunset** [readbeyond/aeneas#240]
python -m aeneas.tools.execute_task --example-json

this is my output json file

{
 "fragments": [
  {
   "begin": "0.000",
   "children": [],
   "end": "2.880",
   "id": "f000001",
   "language": "eng",
   "lines": [
    "1"
   ]
  },
  {
   "begin": "2.880",
   "children": [],
   "end": "7.280",
   "id": "f000002",
   "language": "eng",
   "lines": [
    "From fairest creatures we desire increase,"
   ]
  },
  {
   "begin": "7.280",
   "children": [],
   "end": "11.600",
   "id": "f000003",
   "language": "eng",
   "lines": [
    "That thereby beauty's rose might never die,"
   ]
  },
  {
   "begin": "11.600",
   "children": [],
   "end": "16.480",
   "id": "f000004",
   "language": "eng",
   "lines": [
    "But as the riper should by time decease,"
   ]
  },
  {
   "begin": "16.480",
   "children": [],
   "end": "20.000",
   "id": "f000005",
   "language": "eng",
   "lines": [
    "His tender heir might bear his memory:"
   ]
  },
  {
   "begin": "20.000",
   "children": [],
   "end": "24.480",
   "id": "f000006",
   "language": "eng",
   "lines": [
    "But thou contracted to thine own bright eyes,"
   ]
  },
  {
   "begin": "24.480",
   "children": [],
   "end": "31.720",
   "id": "f000007",
   "language": "eng",
   "lines": [
    "Feed'st thy light's flame with self-substantial fuel,"
   ]
  },
  {
   "begin": "31.720",
   "children": [],
   "end": "35.480",
   "id": "f000008",
   "language": "eng",
   "lines": [
    "Making a famine where abundance lies,"
   ]
  },
  {
   "begin": "35.480",
   "children": [],
   "end": "41.800",
   "id": "f000009",
   "language": "eng",
   "lines": [
    "Thy self thy foe, to thy sweet self too cruel:"
   ]
  },
  {
   "begin": "41.800",
   "children": [],
   "end": "47.400",
   "id": "f000010",
   "language": "eng",
   "lines": [
    "Thou that art now the world's fresh ornament,"
   ]
  },
  {
   "begin": "47.400",
   "children": [],
   "end": "51.560",
   "id": "f000011",
   "language": "eng",
   "lines": [
    "And only herald to the gaudy spring,"
   ]
  },
  {
   "begin": "51.560",
   "children": [],
   "end": "53.200",
   "id": "f000012",
   "language": "eng",
   "lines": [
    "Within thine own bud buriest thy content,"
   ]
  },
  {
   "begin": "53.200",
   "children": [],
   "end": "53.200",
   "id": "f000013",
   "language": "eng",
   "lines": [
    "And tender churl mak'st waste in niggarding:"
   ]
  },
  {
   "begin": "53.200",
   "children": [],
   "end": "53.200",
   "id": "f000014",
   "language": "eng",
   "lines": [
    "Pity the world, or else this glutton be,"
   ]
  },
  {
   "begin": "53.200",
   "children": [],
   "end": "53.240",
   "id": "f000015",
   "language": "eng",
   "lines": [
    "To eat the world's due, by the grave and thee."
   ]
  }
 ]
}

**Comment by pettarin** [comment]
If you are running on Windows --- which is not officially supported, BTW --- you are likely affected by this defect: https://github.com/readbeyond/aeneas/issues/190
