### ISSUE TITLE
Current state of the project

### ISSUE THREAD

**Issue by DonaldTsang** [readbeyond/aeneas#241]
@pettarin if you are reading this, please let @michaelh-sc @mgaitan update the project, since there are space for improvement, even if the company is closed (https://www.readbeyond.it/press/pr008.html)

**Comment by pettarin** [comment]
Thank you for your interest in aeneas.

I am not sure if you noticed, but I have kept updating, maintaining, and documenting aeneas well after ReadBeyond was shut down. Simply, in the last two years or so, I have less time to dedicate to FLOSS activities.

Currently the pull requests tab at https://github.com/readbeyond/aeneas/pulls has zero open PRs. In the past I have always vetted and merged meaningful PRs (see https://github.com/readbeyond/aeneas/pulls?q=is%3Apr+is%3Aclosed ). If you or one of your associates (are the other developers you mention associates of yours?) want to submit a PR, I will be happy to evaluate and merge it, if useful and in line with the technical standards of the project.

**Comment by DonaldTsang** [comment]
@pettarin those are not associates but rather community contributors who did not PR their code, since they added some key libraries in order to update Python 3. It might be a good idea to examine them. You can see some of them in https://github.com/readbeyond/aeneas/network

**Comment by pettarin** [comment]
> It might be a good idea to examine them. 

It does not work like that. If someone thinks that she or he has code that would fix a bug or add a functionality, they should open a pull request, I will be glad to examine it, and see if it meets the technical requirements of the project.

The time I can dedicate to FLOSS contributions is limited, so I cannot simply "go check https://github.com/readbeyond/aeneas/network ".

As said above: if someone has made changes in their own fork of aeneas, but they did not open a PR into the upstream, then I see two explanations: either they needed a fix or a feature specific for their needs, in which case it is unlikely it will be interesting for the entire project; or they do not care contributing back, and accepting a PR from someone who does not care is a maintenance liability long term.

In any case, I cannot force _anyone else_ to submit their patches, and I _cannot_ pull patches into the upstream repository without the consent of the author of those patches.
