### ISSUE TITLE
Put end boundary in middle of silence

### ISSUE THREAD

**Issue by george-roussos** [readbeyond/aeneas#252]
Hi,

This tool is very mighty. I am trying to use it with Swedish, and for the most part it works okay. However, the end boundary almost always falls on breath segment, or the beginning of the next fragment, and so there is interference in the alignments. Is there any way to instruct aeneas to only put the boundary on a silent part? For example, right now if there is silence, it is all included in the previous fragment; it would be nice if it could be evenly split.

Thanks!

**Comment by pettarin** [comment]
https://www.readbeyond.it/aeneas/docs/adjustboundaryalgorithm.html

Nice to see interest from (people from) Storytel...

**Comment by george-roussos** [comment]
Thanks! And thanks a bunch for this amazing tool 😀
