### ISSUE TITLE
[macOS] brew suggeted by wiki/INSTALL.md is broken

### ISSUE THREAD

**Issue by talaviram** [readbeyond/aeneas#254]
Trying on Mojave with updated brew results:

```
 brew install danielbair/tap/aeneas
Warning: Calling 'devel' blocks in formulae is deprecated! Use 'head' blocks or @-versioned formulae instead.
Please report this issue to the danielbair/tap tap (not Homebrew/brew or Homebrew/core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/danielbair/homebrew-tap/aeneas.rb:7

==> Installing aeneas from danielbair/tap
Error: No available formula with the name "python@2" (dependency of danielbair/tap/aeneas)
==> Searching for a previously deleted formula (in the last month)...
```

I'll look for `danielbair` but I'm logging it here so maybe someone within the project itself might be faster to resolve this.

Suggested here (as a workaround) -

https://stackoverflow.com/questions/60298514/brew-reinstalling-python2

```
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/86a44a0a552c673a05f11018459c9f5faae3becc/Formula/python@2.rb
```

but it seems the project itself already supports Python3.5 so the isn't nice.

**Comment by talaviram** [comment]
Seems simplest on macOS is just using pip3 based and not brew.
Though would be nice to update the INSTALL.md. (the reason I'm not closing this issue)

**Comment by danielbair** [comment]
Ok. I will look into fixing the formula ASAP.


-- 
[image:
https://lh4.googleusercontent.com/-wIrA61rE_y4/AAAAAAAAAAI/AAAAAAAAAAA/EadW_TiIByg/s64-c/photo.jpg]
Daniel Bair, Director, Thailand Gospel Media Project
| m. 081-362-1520 | h. 817-264-6456 | o. 053-995-453
| e. missions@danielbair.com | w. missions.danielbair.com

**Comment by danielbair** [comment]
Ok, I have updated the aeneas formula to python 3.8 because the homebrew team has locked the numpy formula to python 3.8 also.

**Comment by micahmills** [comment]
I get the following error when I tried the brew install

`curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "aeneas"
Download failed: https://github.com/danielbair/homebrew-tap/releases/download/bottles/aeneas-1.7.3_4.yosemite.bottle.tar.gz`

**Comment by danielbair** [comment]
Sorry, I will get that bottle built and uploaded shortly.
In the meantime just do:
`brew install -s aeneas`

**Comment by micahmills** [comment]
The installer worked but when I try to run an example from the command line it is telling me No module name 'aeneas' is found.

I probably need to open a separate issue.

**Comment by danielbair** [comment]
That is probably because it installs python3.8 which isn't linked into the system. I had to use python3.8 because the homebrew maintainers have built numpy against python3.8 now.

**Comment by micahmills** [comment]
I linked python3.8 and that didn't fix it but I realized I was running the command using `python`  when I used `python3` it worked.

**Comment by talaviram** [comment]
Yep python3 is common as until 10.15 at least python is built-in.

**Comment by danielbair** [comment]
Try setting python3.8 as default like this:
`brew link --force --overwrite python@3.8`
