### ISSUE TITLE
Error install ffmpeg on macos 10.12

### ISSUE THREAD

**Issue by Liranbz** [readbeyond/aeneas#256]
I try to install ffmpeg for macos 10.12 with this command:
`brew install ffmpeg`
and I got this msg:

```
forte:aeneas mac$ brew install ffmpeg
Warning: You are using macOS 10.12.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience while you are running this old version.

libbluray: Java 1.8 is required to install this formula.
Install AdoptOpenJDK 8 with Homebrew Cask:
  brew cask install homebrew/cask-versions/adoptopenjdk8
Error: An unsatisfied requirement failed this build.
```

This is caused to this error:

```
forte:aeneas mac$ python aeneas_check_setup.py
[INFO] aeneas         OK
[ERRO] ffprobe        ERROR
[INFO]   Please make sure you have ffprobe installed correctly
[INFO]   (usually it is provided by the ffmpeg installer)
[INFO]   and that its path is in your PATH environment variable
```
What I need to do?

**Comment by danielbair** [comment]
Just follow what it says to do...
`brew cask install homebrew/cask-versions/adoptopenjdk8`
And then retry `brew install ffmpeg` again.

If it still won't install, you have a couple of options:
1.  You can try to install an older version of the homebrew formula from `brew log ffmpeg` by finding a version about a year or two old and then use `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/<replace_with_commit_string>/Formula/ffmpeg.rb` by replacing "<replace_with_commit_string>" with the commit string you found from "brew log ffmpeg"
2. Download static binaries from [https://evermeet.cx/ffmpeg/](https://evermeet.cx/ffmpeg/)
3. Use the aeneas "all in one installer" for mac from [https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md](https://github.com/readbeyond/aeneas/blob/master/wiki/INSTALL.md)

**Comment by Liranbz** [comment]
Oh I missed it! Thank you!
