### ISSUE TITLE
How to deal with "Segmentation fault" ?

### ISSUE THREAD

**Issue by sunjianan9900** [readbeyond/aeneas#261]
[demos.zip](https://github.com/readbeyond/aeneas/files/5140967/demos.zip)

python -m aeneas.tools.execute_task 200828-143453104159_1.mp3 srt.txt  "task_language=eng|os_task_file_format=json|is_text_type=plain" map.json

`[INFO] Validating config string (specify --skip-validator to bypass)...
[INFO] Validating config string... done
[INFO] Creating task...
[INFO] Creating task... done
[INFO] Executing task...
Segmentation fault`

**Comment by readbeyond** [comment]
Please run with the verbose flag, and post its output. Also: what OS / version of python / version of aeneas are you running?

**Comment by readbeyond** [comment]
Your MP3 file is likely too long (1h38m) for the RAM available on your machine, likely the segmentation fault happens because the cdtw cannot allocate enough memory.
