### ISSUE TITLE
Trouble using festival backend

### ISSUE THREAD

**Issue by polm** [readbeyond/aeneas#266]
I have Festival installed and working on Arch Linux, but it doesn't work as an aeneas backend. The language argument (`(language_english)`) causes an error. I'm not sure if this is due to some kind of version change in Festival or what. This is the festival error:

    SIOD ERROR: unbound variable : language_english

Commenting out the part of the code that uses the language argument so that the default voice is used makes it work. 

Is there any other information I can provide to help troubleshoot this? Commenting stuff out is working for my use, but I'd be glad to help fix it if possible.

**Comment by readbeyond** [comment]
@polm are you sure you have some English festival voice installed? On my Debian box:

```
$ festival
festival> (language_english)
rab_diphone
festival> (SayText "Hello world")    
#<Utterance 0x7f0a8dd508d0>
festival> (language_foo)
SIOD ERROR: unbound variable : language_foo
festival> 
```

**Comment by polm** [comment]
I am on Arch Linux and have installed the following packages:

- festival
- festival-us
- festival-english

Using autocomplete, it looks like festival has `language_american_english` and `language_british_english` but not `language_english`. However executing either of the two commands gives an error like this:

    SIOD ERROR: unbound variable : voice_ked_diphone

American fails with "ked" as above, British fails with "don" instead of "ked". 

Not really sure why this is happening... festival definitely has the ability to generate audio reasonably, as mentioned using the default voice with aeneas works and `text2wave` works fine.

**Comment by polm** [comment]
This seems like the same issue: 

https://bugs.launchpad.net/ubuntu/+source/festival/+bug/688940

My festival version is 2.5.0, which is after the supposed fix mentioned at the end of that ticket.

**Comment by polm** [comment]
After working with this more it seems like something is wrong with the way the Arch Linux packages set up the voices. I don't understand exactly what it is but it has nothing to do with aeneas; sorry for the false alarm.
