### ISSUE TITLE
Misaligned output

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [readbeyond/aeneas#269]
Hello.

I am offering 

1. a plain text file with one sentence each line. UTF-8 No bom. German.
2. an ogg file. German.

to aeneas, installed with the installer for windows.

My command

`python -m aeneas.tools.execute_task "C:\Test03.ogg" "C:\Test03.txt" "task_language=deu|is_text_type=plain|os_task_file_format=srt" "C:\Test03.srt" `

The output srt is misaligned without system(f.i. everything shifted by 5 seconds).

I changed task_language to english, just to see what happens.

The same result.

Conclusion: The language DEU does not exist or is not being used.

Also, I noticed several 00:21:15,360 --> 00:21:15,360 => inpoint = outpoint

Also interesting: https://aeneasweb.org/ works with the same files flawlessly.

Without sharing the 13k lines debug output, what is the likely reason?

**Comment by readbeyond** [comment]
Windows is not officially supported. There are known problems since 1.7.1, see e.g. https://github.com/readbeyond/aeneas/issues/190

The aeneas Web app runs on Linux, that explains why it works there.

Try installing aeneas on Vagrant/Docker. Maybe even the WSL for Windows 10 might work.

**Comment by ErfolgreichCharismatisch** [comment]
The wsl version worked. Very useful advice!
