### ISSUE TITLE
Aeneas and Python3

### ISSUE THREAD

**Issue by yakob-aleksandrovich** [readbeyond/aeneas#36]
Hi there,

I have not dived yet into the actual aeneas code, but I'd like to get things clear before doing that.
For testing purposes, I wanted to include it in a Python 3 project, but that choked on the beautifulsoup version (3.2.1) that it required.
* Am I correct that aeneas only runs in Python 2? 
* Could Aeneas work with a higher version of BS? 
* How much would it take to rework Aeneas into a Py 3 version?

Thanks a lot

**Comment by pettarin** [comment]
On 12/25/2015 07:46 PM, Яков Александрович wrote:
> Hi there,
>
> I have not dived yet into the actual aeneas code, but I'd like to get
> things clear before doing that
> For testing purposes, I wanted to include it in a Python 3 project, but
> that choked on the beautifulsoup version (321) that it required
>
>   * Am I correct that aeneas only runs in Python 2?

Yes, at the moment it runs on Python 2.7.x only.

>   * Could Aeneas work with a higher version of BS?
>   * How much would it take to rework Aeneas into a Py 3 version?

I am actually porting it to run on both 2.7.x and 3.4 or higher, I plan 
to be done around mid January. It will also shift from BeautifulSoup 3 
to BeautifulSoup 4.

Details on this post on the aeneas mailing list (which you might want to 
join to be kept up to date):

https://groups.google.com/d/msg/aeneas-forced-alignment/J_a-avMw28k/NKnFPp3pBwAJ

AP

**Comment by yakob-aleksandrovich** [comment]
And of course, I should have read further before posting this. As it seems, it **is** Python2, since Pettarin is porting to 3 :wink:

**Comment by readbeyond** [comment]
@yakob-aleksandrovich You can find the Port to Python 3 (3.4 or 3.5) on the `port3` branch. Details here: https://groups.google.com/d/msg/aeneas-forced-alignment/J_a-avMw28k/Xlfm0YjfDAAJ
