### ISSUE TITLE
Creating a Path class or some path sanitize functions

### ISSUE THREAD

**Issue by pettarin** [readbeyond/aeneas#43]
Right now paths are treated as (Unicode) strings, and this might pose problems for all the nefarious Windows issues we all know.

Perhaps it is worth considering creating a specialized class or some path sanitize functions in ``globalfunctions.py``.

A specialized class has the advantage of making e.g. "slash conversion" (``/`` => ``\`` on Windows) transparent to the rest of the code. But perhaps it is overkill and global functions will suffice.

**Comment by readbeyond** [comment]
No longer sure this is really useful. Keeping open, but removing from milestone.
