### ISSUE TITLE
Compiling C extensions on Windows and Python 3.4/3.5

### ISSUE THREAD

**Issue by pettarin** [readbeyond/aeneas#44]
After a preliminary search, it looks like there is no equivalent of "Microsoft Visual C++ compiler for Python 2.7" for Python 3.

One must install the correct Microsoft Visual Studio or Visual C/C++ (free, but several GB of download...), as described here:

https://matthew-brett.github.io/pydagogue/python_msvc.html

or

http://stackoverflow.com/questions/29909330/microsoft-visual-c-compiler-for-python-3-4

before being able of compiling Python C extensions.

Investigate this further.

**Comment by readbeyond** [comment]
Closing, as this will be (somewhat) covered by .exe built with pyinstaller.
