### ISSUE TITLE
Replace scikits.audiolab with scipy.io.wavfile

### ISSUE THREAD

**Issue by pettarin** [readbeyond/aeneas#6]
The dependency from `scikits.audiolab` seems to cause a lot of issues to non-Debian users. Moving to something more standard, like `scipy.io.wavfile` might help eliminate these issues.

**Comment by pettarin** [comment]
A user pointed out that the Windows whl for `scipy` is ~90 MB, while `scikits.audiolab` is <1 MB. On the other hand, some non-deb Linux users (Gentoo, Fedora) had difficulties installing `scikits.audiolab`, due to its dependence from `libsnd`.

In my private devel branch I have just replaced `wavread` and `wavwrite` from `scikits.audiolab` with `read` and `write` from `scipy.io.wavfile` after copying verbatim `wavfile.py`.

-1 dependency, yeah!

**Comment by readbeyond** [comment]
Done
