### ISSUE TITLE
Please update debian/changelog?

### ISSUE THREAD

**Issue by chrisvire** [readbeyond/aeneas#84]
Hello Alberto,

Thank you for all the work you have been doing with Aeneas!  It is great work.  

We would like to update the package the we build of Aeneas that gets used by Scripture App Builder and Reading App Builder.  Could you update the debian/changelog and create an entry for 1.5.0.3 and include the changes in the log that you think are relevant?  You have done such a great job of including information about changes for previous entries in the changelog.  I could try to come up with a list, but I don't know whether I could get a good list.

Thanks,

Chris Hubbard

**Comment by pettarin** [comment]
Sure. The very next few days are busy for me, but I will update the Debian stuff during the weekend.

**Comment by chrisvire** [comment]
Thank you very much.  That would be fine.

**Comment by readbeyond** [comment]
Done, I have updated the changelog for Debian. Closing.
