### ISSUE TITLE
Remove linux-only blocks for aeneas.cew

### ISSUE THREAD

**Issue by danielbair** [readbeyond/aeneas#89]
Please remove the linux-only blocks for aeneas.cew now.
I have merged the patches from https://github.com/pettarin/espeakosx into the homebrew espeak to compile and install libespeak.
I've submitted a pull request against the espeak.rb formula, but now homebrew maintainers are considering dropping espeak from their official formula list, see https://github.com/Homebrew/homebrew-core/pull/2726 so it may be necessary to use my homebew tap from now on.

Add the tap:
`brew tap danielbair/tap`
Then install as any other formula:
`brew install danielbair/tap/espeak`

Mac and Windows installers are available for aeneas from https://github.com/sillsdev/aeneas-installer/releases with cew compiled and working!

**Comment by pettarin** [comment]
Continuing the conversation on #90 thread.
